### ISSUE TITLE
É necessário adicionar as datas das antifonas de Nossa Senhora

### ISSUE THREAD

**Issue by ofrades** [ofrades/tesourofieis#25]
https://tesourofieis.com/antifonas

[Alma Redemptoris Mater](https://en.wikipedia.org/wiki/Alma_Redemptoris_Mater) ([Advent](https://en.wikipedia.org/wiki/Advent) through [Candlemas](https://en.wikipedia.org/wiki/Candlemas))
[Ave Regina caelorum](https://en.wikipedia.org/wiki/Ave_Regina_caelorum) (After Candlemas through [Holy Saturday](https://en.wikipedia.org/wiki/Holy_Saturday))
[Regina Caeli](https://en.wikipedia.org/wiki/Regina_Caeli) ([Eastertide](https://en.wikipedia.org/wiki/Easter_season))
[Salve Regina](https://en.wikipedia.org/wiki/Salve_Regina) (After Eastertide through [None](https://en.wikipedia.org/wiki/None_(liturgy)) of the Saturday before [Advent](https://en.wikipedia.org/wiki/Advent))

**Comment by cegalvao** [comment]
#41
